# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e85c73002717c6bddd1e491add965f2a43802fe4b2b8d5c7da9bdfd13fff5e58d4eeb9362d743027f86ede923fff23c05831cad2637e21f6ff3d9e9e1042fa4

test:
  secret_key_base: 0f617ff324093949c3487981aef662c36849f90f1f87147ff49bef91ba02f28d47cf5456ace544a29931e50647024f289094dca48a5219e782414f1704808032

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
